<a href="https://colab.research.google.com/github/gabrieldasneves/ML_studies/blob/master/my_DS_studies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introdução ao Numpy

Biblioteca voltada para a manipulação de matrizes. Contém um conjunto de métodos e funções para trabalhar sobre os `arrays`.

Importando:


In [2]:
import numpy as np

#Trabalhando com vetores:

In [4]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [8]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(5) #tem outras funções predefinidas para criar vetores também

array([0., 0., 0., 0., 0.])

método shape:

In [14]:
vector = np.array([3,3,3,3,3])
vector.shape

(5,)

Operações algébricas:

In [15]:
ex =  np.array([2,4,6,8,10])


In [16]:
ex*5

array([10, 20, 30, 40, 50])

In [17]:
ex/2

array([1., 2., 3., 4., 5.])

In [19]:
100/ex # e assim vai....

array([50.        , 25.        , 16.66666667, 12.5       , 10.        ])

Alguns métodos prontos de vetores que são úteis 

In [22]:

ex.shape


(5,)

In [25]:

ex.mean()
# e por ai vai...

6.0

#Matrizes

##Matrizes são apenas vetores, só que com N dimensões

Criando arrays multidimensionais:

In [28]:
np.array([[1,2,3], [4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Curiosidade: é assim que se cria a matriz identidade:

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Assim se obtém a transposta:

In [32]:
np.array([[1,2,3], [4,5,6],[7,8,9]]).T # com o T no final

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
algumas funções da algebra linear já estão implementadas no numpy, ex:

In [36]:

np.linalg.inv(np.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])